# Main Configuration File for Adaptive Data Quality Framework

framework:
  name: "Adaptive Data Quality Framework"
  version: "1.0.0"
  implementation_phase: "phase1"
  environment: "development"
  created: "2025-01-09"
  author: "O-RAN Data Quality Team"

# Data Source Configuration with Schema
data_sources:
  viavi_dataset:
    enabled: true
    cell_reports_file: "data/raw/CellReports_v0.csv"
    ue_reports_file: "data/raw/UEReports_v0.csv"
    expected_entities:
      cells: 52
      ues: 48
    measurement_interval_seconds: 60

dataset_expectations:
  # Expected patterns from VIAVI dataset analysis
  patterns:
    mimo_zero_rate: 
      expected: 0.86
      description: "Fraction of records with MIMO disabled"
    cqi_no_measurement_rate:
      expected: 0.60
      description: "Fraction of UE records with no CQI measurement"
    ul_dl_symmetry:
      expected: 0.87
      description: "Correlation between UL and DL throughput"
  
  # Expected correlations between metrics
  correlations:
    prb_dl_to_throughput_dl:
      metrics: ['RRU.PrbUsedDl', 'DRB.UEThpDl']
      expected: 0.85
      tolerance: 0.30
    power_to_prb_dl:
      metrics: ['PEE.AvgPower', 'RRU.PrbUsedDl'] 
      expected: 0.72
      tolerance: 0.30
    connections_to_throughput:
      metrics: ['RRC.ConnMean', 'DRB.UEThpDl']
      expected: 0.68
      tolerance: 0.30
  
  # Temporal patterns
  temporal:
    minute_variation_coefficient: 0.15
    hour_variation_coefficient: 0.30
    peak_hour_percentile: 0.70  # Top 30% load hours are peak
  
  # Physical/protocol limits (never change)
  physical_limits:
    cqi_range: [0, 15]
    spectral_efficiency_max: 30.0  # bps/Hz theoretical limit
    connection_max: 255
        
    # Column mappings
    column_names:
      timestamp: 'timestamp'
      cell_entity: 'Viavi.Cell.Name'
      ue_entity: 'Viavi.UE.Name'
    
    # Metric groups for processing
    metric_groups:
      prb_metrics: ['RRU.PrbUsedDl', 'RRU.PrbUsedUl', 'RRU.PrbAvailDl', 'RRU.PrbAvailUl', 'RRU.PrbTotDl', 'RRU.PrbTotUl']
      throughput_metrics: ['DRB.UEThpDl', 'DRB.UEThpUl']
      cqi_metrics: ['DRB.UECqiDl', 'DRB.UECqiUl']
      energy_metrics: ['PEE.AvgPower', 'PEE.Energy']
      connection_metrics: ['RRC.ConnMean', 'RRC.ConnMax']
      mimo_metrics: ['RRU.MaxLayerDlMimo', 'CARR.AverageLayersDl']
      tb_metrics_unreliable: ['TB.TotNbrDl', 'TB.TotNbrUl']
      qos_flow_metrics: ['QosFlow.TotPdcpPduVolumeDl', 'QosFlow.TotPdcpPduVolumeUl']
    
    # Known data issues
    data_quirks:
      tb_counters_unreliable: true
      cqi_zero_is_no_measurement: true
      prb_tot_is_percentage: true
      energy_is_cumulative: true
      qos_flow_has_1s_semantics: true
      mobility_metrics_missing: true

# Processing Configuration
processing:
  windowing:
    size_minutes: 5
    overlap_percent: 80
    minimum_completeness: 0.95
    validation_enabled: true
    
  unit_conversion:
    prb_percentage_to_absolute: true
    energy_cumulative_to_interval: true
    qos_flow_validation: true
    validation_tolerance: 0.20
    
  feature_extraction:
    statistical_features: true
    temporal_features: true
    correlation_features: true
    normalization_method: "z_score"

# Quality Assessment Configuration
quality_assessment:
  dimensions:
    completeness: true
    consistency: true
    accuracy: true
    timeliness: true
    skewness: true
    
  scoring:
    traditional_scoring: true
    ml_scoring: false  # Enable after Phase 2
    pca_consolidation: false  # Enable after Phase 2
    
  baselines:
    auto_update: false
    validation_required: true
    backup_previous: true


quality_dimension_thresholds:
  completeness:
    C1_mandatory_fields:
      pass: 0.95  # ≥95% rows have all mandatory fields
      soft: 0.80  # 80-95% rows have all mandatory fields
    C2_entity_coverage:
      cells:
        pass: 0.95  # ≥95% of expected cells (from HoD baseline)
        soft: 0.85  # 85-95% of expected cells
      ues:
        pass: 0.80  # ≥80% of expected UEs (from HoD baseline)
        soft: 0.60  # 60-80% of expected UEs
    C3_temporal_coverage:
      pass: 5     # 5 timestamps (complete)
      soft: 4     # 4 timestamps (minimum acceptable)
    C4_field_completeness:
      pass: 0.80  # ≥80% fields have <20% nulls
      soft: 0.60  # 60-80% fields have <20% nulls
      null_threshold: 0.20  # Field considered complete if <20% nulls
      
  validity:
    V1_data_type_range:
      pass: 0.99  # ≥99% values in valid ranges
      soft: 0.95  # 95-99% in valid ranges
    V2_prb_identity:
      pass: 0.95  # Identity holds for ≥95% rows
      soft: 0.80  # Holds for 80-95% rows
      tolerance_pp: 2  # ±2 percentage points
    V3_prb_usage_limits:
      pass: 1.00  # 100% rows satisfy constraint
      soft: 0.95  # 95-100% satisfy
    V4_business_rules:
      pass: 0.99  # All rules satisfied ≥99%
      soft: 0.95  # Satisfied 95-99%
    V5_energy_sanity:
      pass: 0.90  # Ratio valid for ≥90% rows
      soft: 0.70  # Valid for 70-90% rows
      ratio_range: [0.5, 2.0]  # Acceptable energy/power ratio
      
  accuracy:
    A1_throughput_per_prb:
      pass: 450   # ≤450 Mbps per 100% PRB
      soft: 600   # 450-600 Mbps warning
    A2_spectral_efficiency:
      pass: 30    # SE < 30 bps/Hz
      soft: 35    # SE < 35 bps/Hz
    A3_context_validation:
      pass: 0     # No violations
      soft: 2     # 1-2 minor violations
    A4_pattern_conformance:
      pass: 0.10  # Within ±10% of expected patterns
      soft: 0.20  # Within ±20% of expected
      
  consistency:
    CS1_intra_record:
      pass: 0.99  # Constraints satisfied ≥99%
      soft: 0.95  # Satisfied 95-99%
    CS2_energy_physics:
      pass: [0.5, 2.0]   # Ratio in this range
      soft: [0.3, 3.0]   # Wider tolerance
    CS3_network_aggregation:
      pass: 0.05  # Differences ≤5%
      soft: 0.10  # Differences 5-10%
    CS4_temporal_smoothness:
      pass: 0     # No suspicious transitions
      soft: 2     # 1-2 suspicious transitions
      
  timeliness:
    T1_on_time_percentage:
      pass: 0.95  # ≥95% on-time
      soft: 0.80  # 80-95% on-time
      delay_threshold_seconds: 60
    T2_p95_delay:
      pass: 60    # P95 ≤ 60 seconds
      soft: 120   # P95 ≤ 120 seconds
    T3_update_frequency:
      pass: 0.90  # ≥90% intervals correct
      soft: 0.80  # 80-90% correct
      expected_interval: 60
      tolerance: 5  # ±5 seconds
    T4_out_of_order:
      pass: 0.01  # OOO ≤1%
      soft: 0.02  # OOO 1-2%
      
  skewness:  # Monitoring only - not in composite score
    S1_statistical_skewness:
      pass: 0.5   # Deviation <0.5 from baseline
      soft: 2.0   # Deviation 0.5-2.0
    S2_jsd_divergence:
      pass: 0.1   # JSD <0.1
      soft: 0.3   # JSD 0.1-0.3
    S3_outlier_clustering:
      pass: "random"      # Outliers randomly distributed
      soft: "clustered"   # Some clustering detected

# Drift Detection Configuration
drift_detection:
  enabled: false  # Enable in Phase 3
  config_file: "config/drift_thresholds.yaml"
  monitoring_metrics:
    - "RRU.PrbUsedDl"
    - "RRU.PrbUsedUl" 
    - "DRB.UEThpDl"
    - "DRB.UEThpUl"
    - "RRC.ConnMean"
    - "PEE.AvgPower"
    - "DRB.UECqiDl"

# Machine Learning Configuration
machine_learning:
  enabled: false  # Enable in Phase 2
  model_type: "xgboost"
  hyperparameter_tuning: true
  validation_split: 0.2
  cross_validation_folds: 5
  artifact_versioning: true

# External Configuration Files
external_configs:
  band_specifications: "config/band_configs.json"
  drift_thresholds: "config/drift_thresholds.yaml"
  logging_config: "config/logging_config.yaml"

# Storage Configuration
storage:
  artifacts:
    base_path: "data/artifacts"
    versioning_enabled: true
    compression: true
    max_versions_keep: 10
    
  processed_data:
    format: "parquet"
    compression: "snappy"
    base_path: "data/processed"
    
  logs:
    base_path: "data/logs"
    retention_days: 30
    level: "INFO"
    file_rotation: true

# Performance Configuration
performance:
  memory:
    max_windows_in_memory: 1000
    garbage_collection_frequency: 100
    large_file_threshold_mb: 100
    
  processing:
    parallel_processing: false
    max_workers: 4
    chunk_size: 1000
    
  caching:
    enabled: true
    cache_size_mb: 512
    cache_artifacts: true

# Validation and Testing
validation:
  data_validation:
    strict_mode: true
    mandatory_fields_check: true
    range_validation: true
    pattern_validation: true
    
  model_validation:
    enabled: false
    validation_metrics: ["mae", "r2"]
    acceptance_thresholds:
      mae: 0.15
      r2: 0.85

# Phases Configuration
phases:
  phase1:
    focus: "data_preparation_and_baselines"
    required_components: ["data_loader", "unit_converter", "window_generator"]
    output_artifacts: ["statistical_baselines", "historical_pdfs", "pattern_baselines", "temporal_templates", "field_ranges", "metadata_config", "sample_windows"]
    validation_required: true
    
  phase2:
    focus: "quality_scoring_and_ml_training"
    enabled: false
    required_components: ["quality_dimensions", "pca_consolidator", "model_trainer"]
    depends_on_phase1: true
    
  phase3:
    focus: "drift_detection_and_adaptation"
    enabled: false
    required_components: ["drift_detector", "method_activator"]
    depends_on_phase2: true
    
  phase4:
    focus: "deployment_and_integration"
    enabled: false
    required_components: ["xapp_framework", "kafka_integration"]
    depends_on_phase3: true

# Development Settings
development:
  debug:
    enabled: true
    verbose_logging: true
    save_intermediate_results: true
    validation_reports: true
    
  testing:
    use_synthetic_data: false
    fast_testing_mode: false
    skip_time_consuming_tests: false

# Metadata
metadata:
  config_version: "1.0"
  last_updated: "2025-01-09"
  validation_status: "pending"