# Drift Detection Configuration for Adaptive Data Quality Framework

drift_detection:
  significance_threshold: 0.08
  min_history_size: 100
  max_history_size: 1000
  
  #window_size_minutes: 5
  #sliding_step_minutes: 2
  
  distribution_bins: 50
  jsd_calculation_method: "histogram"
  
  #pattern_recognition:
    #daily_cycle_threshold: 0.15
    #weekly_cycle_threshold: 0.20
    #peak_hours: [8, 9, 10, 11, 16, 17, 18]
    #off_peak_hours: [1, 2, 3, 4, 5, 6]
  
  # Pattern Baseline Tolerances (from VIAVI dataset analysis)
pattern_tolerances:
  mimo_zero_rate: 0.10        # ±10% from observed 86%
  cqi_zero_rate: 0.10         # ±10% from observed 60%
  ul_dl_symmetry: 0.15        # ±15% from observed 87%
  tb_counter_reliability: 0.05 # TB counters mostly unreliable
  prb_tot_percentage_range: [0, 100]  # PrbTot is percentage
  
  adaptation:
    consecutive_detections_required: 3
    cooldown_period_minutes: 60
    confidence_threshold: 0.85



# Metadata
metadata:
  configuration_version: "1.0"
  created_date: "2025-01-09"
  tuning_status: "initial_conservative"